name: Deploy to Development

on:
  push:
    branches:
      - main  # または適切なブランチ名
    # paths:
    # - prisma/migrations/**
    # - prisma/schema.prisma
  workflow_dispatch:

    
jobs:
  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20'
  #         cache: 'npm'

  #     - name: Install Dependencies
  #       run: npm ci
  
  migrate:
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - uses: actions/checkout@v4

      # - name: Setup Supabase CLI
      #   uses: supabase/setup-cli@v1
      #   with:
      #     version: latest

      # - name: Link Supabase Project
      #   run: supabase link --project-ref $SUPABASE_PROJECT_ID --debug

      # - name: マイグレーション
      #   run: supabase db push

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Deploy Prisma Migrations
        run: npx prisma migrate dev
